### ISSUE TITLE
link colors?

### ISSUE THREAD

**Issue by cpuguy83** [antage/formtastic-plus-bootstrap#10]
I added this and suddenly most of my links are blue.
Any particular reason for changing these?

Overwriting this with custom CSS, but curious why it is this way.

**Comment by antage** [comment]
@cpuguy83, I think this is bug. I will check this out.

**Comment by antage** [comment]
@cpuguy83, You have blue (#0088CC) link color because it is default color for links in bootstrap. Take a look at bootstrap's variable `$linkColor`. If you change this variable you'll customize link color.

**Comment by cpuguy83** [comment]
I've been using Bootstrap and I didn't get this until I switched over to this from the formtastic-bootstrap stuff (which, btw, I MUCH prefer this, kudos)

Brian Goff

**Comment by antage** [comment]
@cpuguy83, just try to create test app with bootstrap-sass and without formtastic-plus-bootstrap and you see your links are blue.
Or just take a look at bootstrap source:
https://github.com/twitter/bootstrap/blob/master/less/scaffolding.less#L23
https://github.com/twitter/bootstrap/blob/master/less/variables.less#L41
