### ISSUE TITLE
semantic_errors should have alert classes

### ISSUE THREAD

**Issue by aripollak** [antage/formtastic-plus-bootstrap#11]
The semantic_errors method in formtastic normally just does a `<ul class="errors">`, but I think it would make sense to have it be surrounded by a `<div class="alert alert-error alert-block">`.

**Comment by antage** [comment]
Essentail idea of formtastic-plus-bootstrap is to do not change html code that's generated by formtastic. What's wrong with semantic_errors? Colors?

**Comment by aripollak** [comment]
Yeah, the output from semantic_errors is just a normal bulleted list, with no colors or background to indicate that it's full of errors.
