### ISSUE TITLE
bootstrap-without-forms.css.scss includes bootstrap-responsive

### ISSUE THREAD

**Issue by albertein** [antage/formtastic-plus-bootstrap#14]
Currently there is no way to use formtastic-plus-bootstrap without using a responsive layout since bootstrap-without-forms.css.scss imports bootstrap-responsive css.

That import should be removed from that file and included into formtastic-plus-bootstrap/responsive.

**Comment by antage** [comment]
@albertein Thanks for report! Fixed in 92253fed0f4c3c3ef9df.
