### ISSUE TITLE
Locked at old version of formtastic

### ISSUE THREAD

**Issue by tibbon** [antage/formtastic-plus-bootstrap#18]
```
formtastic-plus-bootstrap (>= 0) ruby depends on
  formtastic (~> 2.2) ruby
```

Yet, 3.1.3 is out.

**Comment by antage** [comment]
@tibbon formtastic 2.3 breaks this gem.
I switched to simple_form + bootstrap 3 because it's too hard to maintain this gem for new versions of formtastic and bootstrap.

If you make formtastic 3 + bootstrap 3 adaption I can place link to your fork in readme.
