### ISSUE TITLE
Twitter bootstrap search form css

### ISSUE THREAD

**Issue by ivanovv** [antage/formtastic-plus-bootstrap#2]
There is special .form-search selector and related css in twitter bootstrap. How can I use it with formtastic-plus-bootstrap?

**Comment by antage** [comment]
I think search forms too simple to use formtastic.
You can't use `bootstrap/forms` in global namespace but you can import it in local namespace.
Look at following example:

`app/views/blabla/example.html`:

``` html
...
<div class="bootstrap-forms">
  <form class="form-search">
    <input type="text" class="input-medium search-query">
    <button type="submit" class="btn">Search</button>
  </form>
</div>
...
```

`app/assets/stylesheets/application.css.scss`:

``` scss
/*
 *= require bootstrap-without-forms
 *= require formtastic-plus-bootstrap
 *= require_self
*/
.bootstrap-forms {
  @import "bootstrap/forms";
}
```

**Comment by antage** [comment]
I added this example in wiki: ["How to use plain bootstrap forms?"](https://github.com/antage/formtastic-plus-bootstrap/wiki/How-to-use-plain-bootstrap-forms%3F)

**Comment by ivanovv** [comment]
I just had to add these two lines to `application.css.scss` right before `.bootstrap-forms {`

```
@import "bootstrap/mixins";
@import "bootstrap/variables";
```

Thanks!

**Comment by antage** [comment]
I fixed this example in the wiki. Thanks!
