### ISSUE TITLE
Is this being actively developed? If not, why? Any better alternatives?

### ISSUE THREAD

**Issue by jensb** [antage/formtastic-plus-bootstrap#20]
I just updated an app of mine from Bootstrap 2 to 3 and Formtastic and lots of other gems and this dependency broke my forms. ;-( Did you ever consider updating this gem for newer Bootstrap and Formtastic versions? If not, what would have to be done? I might just fork it. Thanks!

**Comment by antage** [comment]
@jensb I don't develop this gem because I switched to `simple_form`. Maintaining formtastic css for bootstrap 3.x is too hard.

I recommend to use `simple_form` gem: http://simple-form-bootstrap.plataformatec.com.br/
