### ISSUE TITLE
Bootstrap 2.1 support?

### ISSUE THREAD

**Issue by jensb** [antage/formtastic-plus-bootstrap#9]
There are quite a few (nice) changes in Bootstrap 2.1 and bootstrap-sass is also at 2.1.0.1 already. However, when I include bootstrap-sass 2.1.0.1, I get an error loading it:

```
File to import not found or unreadable: bootstrap/labels.
```

What would need to be done for bootstrap-sass to be upgradeable and compatible with formtastic-plus-bootstrap?

**Comment by antage** [comment]
@jensb, I released new version of the gem for bootstrap-sass >= 2.1.0. Just run `bundle update formtastic-plus-bootstrap` to solve this issue.
